---
apiVersion: v1
kind: Service
metadata:
  name: employee-frontend-svc
  namespace: dev
  labels:
    app: employee-frontend

spec:
  type: ClusterIP
  selector:
    app: employee-frontend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


