---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-sa
  namespace: dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qa-sa
  namespace: qa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-sa
  namespace: prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: jenkins
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-sa
  namespace: argocd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-sa
  namespace: monitoring
