apiVersion: v1
kind: LimitRange
metadata:
  name: jenkins-limitrange
  namespace: jenkins

spec:
  limits:
  - type: Container

    defaultRequest:
      cpu: "200m"
      memory: "256Mi"

    default:
      cpu: "500m"
      memory: "512Mi"
