apiVersion: v1
kind: LimitRange
metadata:
  name: prod-limitrange
  namespace: prod

spec:
  limits:
  - type: Container

    defaultRequest:
      cpu: "500m"
      memory: "512Mi"

    default:
      cpu: "800m"
      memory: "750Mi"
